/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddressId = bigint;
export interface AdminStats {
  'totalOrders' : bigint,
  'ordersByDay' : Array<[string, bigint]>,
  'lowStockCount' : bigint,
  'userGrowthByDay' : Array<[string, bigint]>,
  'totalUsers' : bigint,
  'topProducts' : Array<[bigint, string, bigint]>,
  'pendingReviews' : bigint,
  'totalRevenue' : bigint,
  'totalRevenue30Days' : bigint,
  'activeProducts' : bigint,
  'totalSavingsDistributed' : bigint,
}
export type AgeGatedCategory = { 'Alcohol' : null } |
  { 'Tobacco' : null };
export type BannerId = bigint;
export interface BannerPublic {
  'id' : BannerId,
  'title' : string,
  'imageBlob' : ExternalBlob,
  'displayOrder' : bigint,
  'link' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
}
export type BundleId = bigint;
export interface BundlePublic {
  'id' : BundleId,
  'imageBlob' : ExternalBlob,
  'productIds' : Array<ProductId>,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'bundlePrice' : bigint,
}
export type BuyXGetYRuleId = bigint;
export interface BuyXGetYRulePublic {
  'id' : BuyXGetYRuleId,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'getProductId' : ProductId,
  'getQty' : bigint,
  'buyQty' : bigint,
  'buyProductId' : ProductId,
}
export interface CartItemPublic {
  'userId' : UserId,
  'productId' : ProductId,
  'addedAt' : Timestamp,
  'substituteProductId' : [] | [bigint],
  'quantity' : bigint,
}
export type CategoryId = bigint;
export interface CategoryPublic {
  'id' : CategoryId,
  'displayOrder' : bigint,
  'name' : string,
  'isActive' : boolean,
  'iconEmoji' : string,
}
export interface ChatMessage {
  'id' : ChatMsgId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'sender' : ChatMessageSender,
}
export type ChatMessageSender = { 'admin' : null } |
  { 'user' : null };
export type ChatMsgId = bigint;
export interface ChatThreadPublic {
  'status' : ChatThreadStatus,
  'lastMessageAt' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
}
export type ChatThreadStatus = { 'resolved' : null } |
  { 'open' : null };
export type CouponId = bigint;
export interface CouponPublic {
  'id' : CouponId,
  'discountValue' : bigint,
  'code' : string,
  'discountType' : { 'fixed' : null } |
    { 'percent' : null },
  'usageCount' : bigint,
  'isActive' : boolean,
  'usageLimit' : bigint,
  'expirationDate' : Timestamp,
}
export interface DeliveryAddress {
  'tag' : string,
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export type FlashDealId = bigint;
export interface FlashDealPublic {
  'id' : FlashDealId,
  'discountPercent' : bigint,
  'productId' : ProductId,
  'isActive' : boolean,
  'endDateTime' : Timestamp,
  'startDateTime' : Timestamp,
}
export type InAppNotifId = bigint;
export type InAppNotifType = { 'stockBack' : null } |
  { 'orderStatus' : null } |
  { 'promotion' : null } |
  { 'general' : null } |
  { 'priceDrop' : null };
export interface InAppNotificationPublic {
  'id' : InAppNotifId,
  'title' : string,
  'notifType' : InAppNotifType,
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : [] | [ProductId],
  'isRead' : boolean,
  'orderId' : [] | [OrderId],
}
export type Language = { 'EN' : null } |
  { 'ES' : null } |
  { 'HI' : null };
export type LocationCheckResult = { 'noShopLocations' : null } |
  {
    'withinRadius' : {
      'shopLocationId' : ShopLocationId,
      'distanceKm' : number,
    }
  } |
  { 'outOfRange' : { 'nearestDistanceKm' : number } };
export type LoyaltyReason = { 'referral' : null } |
  { 'admin' : null } |
  { 'purchase' : null } |
  { 'redemption' : null };
export interface LoyaltyTransaction {
  'id' : LoyaltyTxId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'orderId' : [] | [OrderId],
  'pointsChange' : bigint,
  'reason' : LoyaltyReason,
}
export type LoyaltyTxId = bigint;
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'priceAtOrder' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'tax' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'loyaltyPointsRedeemed' : bigint,
  'total' : bigint,
  'buyXGetYSavings' : bigint,
  'deliveryFee' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDelivery' : [] | [Timestamp],
  'totalSavings' : bigint,
  'walletAmountUsed' : bigint,
  'statusHistory' : Array<StatusHistoryEntry>,
  'deliverySlot' : [] | [string],
  'couponId' : [] | [CouponId],
  'items' : Array<OrderItem>,
  'expressDeliveryFee' : bigint,
  'isExpressDelivery' : boolean,
  'subtotal' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PlaceOrderResult = { 'ok' : OrderId } |
  { 'err' : string };
export interface PriceDropAlert {
  'id' : PriceDropAlertId,
  'originalPrice' : bigint,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'alertedUsers' : Array<UserId>,
  'newPrice' : bigint,
}
export type PriceDropAlertId = bigint;
export interface ProductFilters {
  'categoryId' : [] | [CategoryId],
  'minRating' : [] | [bigint],
  'onlyActive' : boolean,
  'maxPrice' : [] | [bigint],
  'minPrice' : [] | [bigint],
  'searchQuery' : [] | [string],
}
export type ProductId = bigint;
export interface ProductPublic {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'imageBlob' : ExternalBlob,
  'stockQty' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'isNewArrival' : boolean,
  'description' : string,
  'ageRestricted' : boolean,
  'isActive' : boolean,
  'bestBeforeDate' : [] | [bigint],
  'isFeatured' : boolean,
  'rating' : bigint,
  'bundleId' : [] | [bigint],
  'price' : bigint,
  'reviewCount' : bigint,
  'isBestSeller' : boolean,
  'harvestDate' : [] | [bigint],
  'ageCategory' : [] | [AgeGatedCategory],
}
export type RecipeId = bigint;
export interface RecipeIngredient {
  'unit' : string,
  'productId' : ProductId,
  'quantity' : number,
}
export interface RecipePublic {
  'id' : RecipeId,
  'imageBlob' : ExternalBlob,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'cookTimeMinutes' : bigint,
  'isActive' : boolean,
  'servings' : bigint,
  'ingredients' : Array<RecipeIngredient>,
}
export type ReviewId = bigint;
export interface ReviewPublic {
  'id' : ReviewId,
  'isApproved' : boolean,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : string,
  'productId' : ProductId,
  'rating' : bigint,
  'helpfulCount' : bigint,
}
export interface SavedAddressPublic {
  'id' : AddressId,
  'tag' : string,
  'zip' : string,
  'street' : string,
  'city' : string,
  'userId' : UserId,
  'state' : string,
  'isDefault' : boolean,
  'phone' : string,
}
export type SeasonalCollectionId = bigint;
export interface SeasonalCollectionPublic {
  'id' : SeasonalCollectionId,
  'imageBlob' : ExternalBlob,
  'endDate' : Timestamp,
  'productIds' : Array<ProductId>,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'startDate' : Timestamp,
}
export type ShopLocationId = bigint;
export interface ShopLocationPublic {
  'id' : ShopLocationId,
  'lat' : number,
  'long' : number,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'deliveryFeeMultiplier' : bigint,
  'radiusKm' : number,
}
export interface StatusHistoryEntry {
  'status' : OrderStatus,
  'timestamp' : Timestamp,
}
export type StockSubId = bigint;
export interface StockSubscription {
  'id' : StockSubId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
}
export type SubscriptionFrequency = { 'monthly' : null } |
  { 'weekly' : null };
export interface SubscriptionItem {
  'productId' : ProductId,
  'quantity' : bigint,
}
export type SubscriptionPlanId = bigint;
export interface SubscriptionPlanPublic {
  'id' : SubscriptionPlanId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'frequency' : SubscriptionFrequency,
  'items' : Array<SubscriptionItem>,
  'pricePerCycle' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPreferencesPublic {
  'userId' : UserId,
  'language' : Language,
  'darkMode' : boolean,
}
export interface UserPublic {
  'id' : UserId,
  'userLong' : [] | [number],
  'referralCode' : string,
  'wishlistShareToken' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'userLat' : [] | [number],
  'email' : string,
  'referredBy' : [] | [UserId],
  'phone' : string,
  'loyaltyBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserSubscriptionId = bigint;
export interface UserSubscriptionPublic {
  'id' : UserSubscriptionId,
  'planId' : SubscriptionPlanId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'nextDeliveryDate' : Timestamp,
  'isActive' : boolean,
  'startDate' : Timestamp,
}
export interface WalletTransaction {
  'id' : WalletTxId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'orderId' : [] | [OrderId],
  'txType' : WalletTxType,
  'amount' : bigint,
}
export type WalletTxId = bigint;
export type WalletTxType = { 'topUp' : null } |
  { 'adminAdjustment' : null } |
  { 'orderDeduction' : null } |
  { 'bonus' : null } |
  { 'refund' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAddress' : ActorMethod<
    [string, string, string, string, string, string],
    AddressId
  >,
  'addShopLocation' : ActorMethod<
    [string, number, number, number, bigint],
    ShopLocationId
  >,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'adminAdjustWallet' : ActorMethod<[Principal, bigint, string], undefined>,
  'adminGetAllWallets' : ActorMethod<[], Array<[Principal, bigint]>>,
  'adminReplyToThread' : ActorMethod<[Principal, string], ChatMsgId>,
  'approveReview' : ActorMethod<[ReviewId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkDeliveryRadius' : ActorMethod<[number, number], LocationCheckResult>,
  'clearCart' : ActorMethod<[], undefined>,
  'createBanner' : ActorMethod<
    [ExternalBlob, string, string, bigint],
    BannerId
  >,
  'createBundle' : ActorMethod<
    [string, string, ExternalBlob, Array<ProductId>, bigint],
    BundleId
  >,
  'createBuyXGetYRule' : ActorMethod<
    [string, ProductId, bigint, ProductId, bigint],
    BuyXGetYRuleId
  >,
  'createCategory' : ActorMethod<[string, bigint, string], CategoryId>,
  'createCoupon' : ActorMethod<
    [
      string,
      { 'fixed' : null } |
        { 'percent' : null },
      bigint,
      Timestamp,
      bigint,
    ],
    CouponId
  >,
  'createFlashDeal' : ActorMethod<
    [ProductId, bigint, Timestamp, Timestamp],
    FlashDealId
  >,
  'createPriceDropAlert' : ActorMethod<
    [ProductId, bigint, bigint],
    PriceDropAlertId
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      CategoryId,
      ExternalBlob,
      bigint,
      boolean,
      boolean,
      boolean,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      boolean,
      [] | [AgeGatedCategory],
    ],
    ProductId
  >,
  'createRecipe' : ActorMethod<
    [string, string, ExternalBlob, bigint, bigint, Array<RecipeIngredient>],
    RecipeId
  >,
  'createSeasonalCollection' : ActorMethod<
    [string, string, ExternalBlob, Array<ProductId>, Timestamp, Timestamp],
    SeasonalCollectionId
  >,
  'createSubscriptionPlan' : ActorMethod<
    [string, string, Array<SubscriptionItem>, bigint, SubscriptionFrequency],
    SubscriptionPlanId
  >,
  'deleteAddress' : ActorMethod<[AddressId], undefined>,
  'deleteBanner' : ActorMethod<[BannerId], undefined>,
  'deleteBundle' : ActorMethod<[BundleId], undefined>,
  'deleteBuyXGetYRule' : ActorMethod<[BuyXGetYRuleId], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteCoupon' : ActorMethod<[CouponId], undefined>,
  'deleteFlashDeal' : ActorMethod<[FlashDealId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'deleteRecipe' : ActorMethod<[RecipeId], undefined>,
  'deleteSeasonalCollection' : ActorMethod<[SeasonalCollectionId], undefined>,
  'deleteShopLocation' : ActorMethod<[ShopLocationId], undefined>,
  'deleteSubscriptionPlan' : ActorMethod<[SubscriptionPlanId], undefined>,
  'generateReferralCode' : ActorMethod<[], string>,
  'generateWishlistShareToken' : ActorMethod<[], string>,
  'getActiveShopLocations' : ActorMethod<[], Array<ShopLocationPublic>>,
  'getAdminBundles' : ActorMethod<[], Array<BundlePublic>>,
  'getAdminBuyXGetYRules' : ActorMethod<[], Array<BuyXGetYRulePublic>>,
  'getAdminSeasonalCollections' : ActorMethod<
    [],
    Array<SeasonalCollectionPublic>
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllChatThreads' : ActorMethod<[], Array<ChatThreadPublic>>,
  'getBanners' : ActorMethod<[], Array<BannerPublic>>,
  'getBestSellers' : ActorMethod<[], Array<ProductPublic>>,
  'getBundleById' : ActorMethod<[BundleId], [] | [BundlePublic]>,
  'getBundles' : ActorMethod<[], Array<BundlePublic>>,
  'getBuyXGetYRules' : ActorMethod<[], Array<BuyXGetYRulePublic>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<CategoryPublic>>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getChatThread' : ActorMethod<[], [] | [ChatThreadPublic]>,
  'getCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'getFeaturedProducts' : ActorMethod<[], Array<ProductPublic>>,
  'getFlashDeals' : ActorMethod<[], Array<FlashDealPublic>>,
  'getInAppNotifications' : ActorMethod<[], Array<InAppNotificationPublic>>,
  'getLoyaltyBalance' : ActorMethod<[], bigint>,
  'getLoyaltyHistory' : ActorMethod<[], Array<LoyaltyTransaction>>,
  'getNewArrivals' : ActorMethod<[], Array<ProductPublic>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getPriceDropAlerts' : ActorMethod<[], Array<PriceDropAlert>>,
  'getProductById' : ActorMethod<[ProductId], [] | [ProductPublic]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<ReviewPublic>>,
  'getProducts' : ActorMethod<[ProductFilters], Array<ProductPublic>>,
  'getProductsByIds' : ActorMethod<[Array<ProductId>], Array<ProductPublic>>,
  'getRecipeById' : ActorMethod<[RecipeId], [] | [RecipePublic]>,
  'getRecipes' : ActorMethod<[], Array<RecipePublic>>,
  'getReviews' : ActorMethod<[boolean], Array<ReviewPublic>>,
  'getSeasonalCollections' : ActorMethod<[], Array<SeasonalCollectionPublic>>,
  'getSharedWishlist' : ActorMethod<[string], Array<ProductId>>,
  'getShopLocations' : ActorMethod<[], Array<ShopLocationPublic>>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlanPublic>>,
  'getThreadMessages' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserAddresses' : ActorMethod<[], Array<SavedAddressPublic>>,
  'getUserCart' : ActorMethod<[], Array<CartItemPublic>>,
  'getUserOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getUserPreferences' : ActorMethod<[], [] | [UserPreferencesPublic]>,
  'getUserPriceDropAlerts' : ActorMethod<[], Array<PriceDropAlert>>,
  'getUserProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getUserStockSubscriptions' : ActorMethod<[], Array<StockSubscription>>,
  'getUserSubscriptions' : ActorMethod<[], Array<UserSubscriptionPublic>>,
  'getUserWishlist' : ActorMethod<[], Array<ProductId>>,
  'getUsers' : ActorMethod<[], Array<UserPublic>>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getWalletBonusConfig' : ActorMethod<[], bigint>,
  'getWalletTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[InAppNotifId], undefined>,
  'placeOrder' : ActorMethod<
    [AddressId, [] | [string], bigint, [] | [string], boolean, bigint],
    PlaceOrderResult
  >,
  'rejectReview' : ActorMethod<[ReviewId], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'resolveThread' : ActorMethod<[Principal], undefined>,
  'searchProducts' : ActorMethod<
    [string, ProductFilters],
    Array<ProductPublic>
  >,
  'sendChatMessage' : ActorMethod<[string], ChatMsgId>,
  'setDefaultAddress' : ActorMethod<[AddressId], undefined>,
  'setProductFreshness' : ActorMethod<
    [ProductId, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'setSubstituteProduct' : ActorMethod<[ProductId, [] | [bigint]], undefined>,
  'setUserLocation' : ActorMethod<[number, number], undefined>,
  'submitReview' : ActorMethod<[ProductId, bigint, string, string], ReviewId>,
  'subscribeToPlan' : ActorMethod<[SubscriptionPlanId], UserSubscriptionId>,
  'subscribeToStockNotification' : ActorMethod<[ProductId], StockSubId>,
  'topUpWallet' : ActorMethod<[bigint], undefined>,
  'triggerStockBackNotifications' : ActorMethod<[ProductId], bigint>,
  'unsubscribeFromPlan' : ActorMethod<[UserSubscriptionId], undefined>,
  'unsubscribeStockNotification' : ActorMethod<[ProductId], undefined>,
  'updateAddress' : ActorMethod<
    [AddressId, string, string, string, string, string, string],
    undefined
  >,
  'updateBanner' : ActorMethod<
    [BannerId, ExternalBlob, string, string, bigint, boolean],
    undefined
  >,
  'updateBundle' : ActorMethod<
    [BundleId, string, string, ExternalBlob, Array<ProductId>, bigint, boolean],
    undefined
  >,
  'updateBuyXGetYRule' : ActorMethod<
    [BuyXGetYRuleId, string, ProductId, bigint, ProductId, bigint, boolean],
    undefined
  >,
  'updateCartQty' : ActorMethod<[ProductId, bigint], undefined>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, bigint, boolean, string],
    undefined
  >,
  'updateCoupon' : ActorMethod<
    [
      CouponId,
      { 'fixed' : null } |
        { 'percent' : null },
      bigint,
      Timestamp,
      boolean,
      bigint,
    ],
    undefined
  >,
  'updateFlashDeal' : ActorMethod<
    [FlashDealId, bigint, Timestamp, Timestamp, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      bigint,
      CategoryId,
      ExternalBlob,
      bigint,
      boolean,
      boolean,
      boolean,
      boolean,
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      boolean,
      [] | [AgeGatedCategory],
    ],
    undefined
  >,
  'updateRecipe' : ActorMethod<
    [
      RecipeId,
      string,
      string,
      ExternalBlob,
      bigint,
      bigint,
      Array<RecipeIngredient>,
      boolean,
    ],
    undefined
  >,
  'updateSeasonalCollection' : ActorMethod<
    [
      SeasonalCollectionId,
      string,
      string,
      ExternalBlob,
      Array<ProductId>,
      Timestamp,
      Timestamp,
      boolean,
    ],
    undefined
  >,
  'updateShopLocation' : ActorMethod<
    [ShopLocationId, string, number, number, number, bigint, boolean],
    undefined
  >,
  'updateSubscriptionPlan' : ActorMethod<
    [
      SubscriptionPlanId,
      string,
      string,
      Array<SubscriptionItem>,
      bigint,
      SubscriptionFrequency,
      boolean,
    ],
    undefined
  >,
  'updateUserPreferences' : ActorMethod<[Language, boolean], undefined>,
  'updateUserProfile' : ActorMethod<[string, string, string], undefined>,
  'updateWalletBonusConfig' : ActorMethod<[bigint], undefined>,
  'validateInviteCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];