/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddressId = IDL.Nat;
export const ShopLocationId = IDL.Nat;
export const ProductId = IDL.Nat;
export const ChatMsgId = IDL.Nat;
export const ReviewId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LocationCheckResult = IDL.Variant({
  'noShopLocations' : IDL.Null,
  'withinRadius' : IDL.Record({
    'shopLocationId' : ShopLocationId,
    'distanceKm' : IDL.Float64,
  }),
  'outOfRange' : IDL.Record({ 'nearestDistanceKm' : IDL.Float64 }),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BannerId = IDL.Nat;
export const BundleId = IDL.Nat;
export const BuyXGetYRuleId = IDL.Nat;
export const CategoryId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CouponId = IDL.Nat;
export const FlashDealId = IDL.Nat;
export const PriceDropAlertId = IDL.Nat;
export const AgeGatedCategory = IDL.Variant({
  'Alcohol' : IDL.Null,
  'Tobacco' : IDL.Null,
});
export const RecipeIngredient = IDL.Record({
  'unit' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Float64,
});
export const RecipeId = IDL.Nat;
export const SeasonalCollectionId = IDL.Nat;
export const SubscriptionItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const SubscriptionFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const SubscriptionPlanId = IDL.Nat;
export const ShopLocationPublic = IDL.Record({
  'id' : ShopLocationId,
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'deliveryFeeMultiplier' : IDL.Nat,
  'radiusKm' : IDL.Float64,
});
export const BundlePublic = IDL.Record({
  'id' : BundleId,
  'imageBlob' : ExternalBlob,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'bundlePrice' : IDL.Nat,
});
export const BuyXGetYRulePublic = IDL.Record({
  'id' : BuyXGetYRuleId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'getProductId' : ProductId,
  'getQty' : IDL.Nat,
  'buyQty' : IDL.Nat,
  'buyProductId' : ProductId,
});
export const SeasonalCollectionPublic = IDL.Record({
  'id' : SeasonalCollectionId,
  'imageBlob' : ExternalBlob,
  'endDate' : Timestamp,
  'productIds' : IDL.Vec(ProductId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'startDate' : Timestamp,
});
export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'ordersByDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'lowStockCount' : IDL.Nat,
  'userGrowthByDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalUsers' : IDL.Nat,
  'topProducts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat)),
  'pendingReviews' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalRevenue30Days' : IDL.Nat,
  'activeProducts' : IDL.Nat,
  'totalSavingsDistributed' : IDL.Nat,
});
export const ChatThreadStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
});
export const UserId = IDL.Principal;
export const ChatThreadPublic = IDL.Record({
  'status' : ChatThreadStatus,
  'lastMessageAt' : Timestamp,
  'userId' : UserId,
  'createdAt' : Timestamp,
});
export const BannerPublic = IDL.Record({
  'id' : BannerId,
  'title' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'displayOrder' : IDL.Nat,
  'link' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
});
export const ProductPublic = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'imageBlob' : ExternalBlob,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isNewArrival' : IDL.Bool,
  'description' : IDL.Text,
  'ageRestricted' : IDL.Bool,
  'isActive' : IDL.Bool,
  'bestBeforeDate' : IDL.Opt(IDL.Int),
  'isFeatured' : IDL.Bool,
  'rating' : IDL.Nat,
  'bundleId' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
  'reviewCount' : IDL.Nat,
  'isBestSeller' : IDL.Bool,
  'harvestDate' : IDL.Opt(IDL.Int),
  'ageCategory' : IDL.Opt(AgeGatedCategory),
});
export const CategoryPublic = IDL.Record({
  'id' : CategoryId,
  'displayOrder' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'iconEmoji' : IDL.Text,
});
export const ChatMessageSender = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : ChatMsgId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'sender' : ChatMessageSender,
});
export const CouponPublic = IDL.Record({
  'id' : CouponId,
  'discountValue' : IDL.Nat,
  'code' : IDL.Text,
  'discountType' : IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
  'usageCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Nat,
  'expirationDate' : Timestamp,
});
export const FlashDealPublic = IDL.Record({
  'id' : FlashDealId,
  'discountPercent' : IDL.Nat,
  'productId' : ProductId,
  'isActive' : IDL.Bool,
  'endDateTime' : Timestamp,
  'startDateTime' : Timestamp,
});
export const InAppNotifId = IDL.Nat;
export const InAppNotifType = IDL.Variant({
  'stockBack' : IDL.Null,
  'orderStatus' : IDL.Null,
  'promotion' : IDL.Null,
  'general' : IDL.Null,
  'priceDrop' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const InAppNotificationPublic = IDL.Record({
  'id' : InAppNotifId,
  'title' : IDL.Text,
  'notifType' : InAppNotifType,
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : IDL.Opt(ProductId),
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(OrderId),
});
export const LoyaltyTxId = IDL.Nat;
export const LoyaltyReason = IDL.Variant({
  'referral' : IDL.Null,
  'admin' : IDL.Null,
  'purchase' : IDL.Null,
  'redemption' : IDL.Null,
});
export const LoyaltyTransaction = IDL.Record({
  'id' : LoyaltyTxId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'orderId' : IDL.Opt(OrderId),
  'pointsChange' : IDL.Int,
  'reason' : LoyaltyReason,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'tag' : IDL.Text,
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
});
export const StatusHistoryEntry = IDL.Record({
  'status' : OrderStatus,
  'timestamp' : Timestamp,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceAtOrder' : IDL.Nat,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'loyaltyPointsRedeemed' : IDL.Nat,
  'total' : IDL.Nat,
  'buyXGetYSavings' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'estimatedDelivery' : IDL.Opt(Timestamp),
  'totalSavings' : IDL.Nat,
  'walletAmountUsed' : IDL.Nat,
  'statusHistory' : IDL.Vec(StatusHistoryEntry),
  'deliverySlot' : IDL.Opt(IDL.Text),
  'couponId' : IDL.Opt(CouponId),
  'items' : IDL.Vec(OrderItem),
  'expressDeliveryFee' : IDL.Nat,
  'isExpressDelivery' : IDL.Bool,
  'subtotal' : IDL.Nat,
});
export const PriceDropAlert = IDL.Record({
  'id' : PriceDropAlertId,
  'originalPrice' : IDL.Nat,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'alertedUsers' : IDL.Vec(UserId),
  'newPrice' : IDL.Nat,
});
export const ReviewPublic = IDL.Record({
  'id' : ReviewId,
  'isApproved' : IDL.Bool,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'productId' : ProductId,
  'rating' : IDL.Nat,
  'helpfulCount' : IDL.Nat,
});
export const ProductFilters = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'minRating' : IDL.Opt(IDL.Nat),
  'onlyActive' : IDL.Bool,
  'maxPrice' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
  'searchQuery' : IDL.Opt(IDL.Text),
});
export const RecipePublic = IDL.Record({
  'id' : RecipeId,
  'imageBlob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'cookTimeMinutes' : IDL.Nat,
  'isActive' : IDL.Bool,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(RecipeIngredient),
});
export const SubscriptionPlanPublic = IDL.Record({
  'id' : SubscriptionPlanId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'frequency' : SubscriptionFrequency,
  'items' : IDL.Vec(SubscriptionItem),
  'pricePerCycle' : IDL.Nat,
});
export const SavedAddressPublic = IDL.Record({
  'id' : AddressId,
  'tag' : IDL.Text,
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'userId' : UserId,
  'state' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
});
export const CartItemPublic = IDL.Record({
  'userId' : UserId,
  'productId' : ProductId,
  'addedAt' : Timestamp,
  'substituteProductId' : IDL.Opt(IDL.Nat),
  'quantity' : IDL.Nat,
});
export const Language = IDL.Variant({
  'EN' : IDL.Null,
  'ES' : IDL.Null,
  'HI' : IDL.Null,
});
export const UserPreferencesPublic = IDL.Record({
  'userId' : UserId,
  'language' : Language,
  'darkMode' : IDL.Bool,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'userLong' : IDL.Opt(IDL.Float64),
  'referralCode' : IDL.Text,
  'wishlistShareToken' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'userLat' : IDL.Opt(IDL.Float64),
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(UserId),
  'phone' : IDL.Text,
  'loyaltyBalance' : IDL.Nat,
});
export const StockSubId = IDL.Nat;
export const StockSubscription = IDL.Record({
  'id' : StockSubId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
});
export const UserSubscriptionId = IDL.Nat;
export const UserSubscriptionPublic = IDL.Record({
  'id' : UserSubscriptionId,
  'planId' : SubscriptionPlanId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'nextDeliveryDate' : Timestamp,
  'isActive' : IDL.Bool,
  'startDate' : Timestamp,
});
export const WalletTxId = IDL.Nat;
export const WalletTxType = IDL.Variant({
  'topUp' : IDL.Null,
  'adminAdjustment' : IDL.Null,
  'orderDeduction' : IDL.Null,
  'bonus' : IDL.Null,
  'refund' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : WalletTxId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'orderId' : IDL.Opt(OrderId),
  'txType' : WalletTxType,
  'amount' : IDL.Int,
});
export const PlaceOrderResult = IDL.Variant({
  'ok' : OrderId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAddress' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AddressId],
      [],
    ),
  'addShopLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
      [ShopLocationId],
      [],
    ),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'adminAdjustWallet' : IDL.Func([IDL.Principal, IDL.Int, IDL.Text], [], []),
  'adminGetAllWallets' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'adminReplyToThread' : IDL.Func([IDL.Principal, IDL.Text], [ChatMsgId], []),
  'approveReview' : IDL.Func([ReviewId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkDeliveryRadius' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [LocationCheckResult],
      ['query'],
    ),
  'clearCart' : IDL.Func([], [], []),
  'createBanner' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Text, IDL.Nat],
      [BannerId],
      [],
    ),
  'createBundle' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Vec(ProductId), IDL.Nat],
      [BundleId],
      [],
    ),
  'createBuyXGetYRule' : IDL.Func(
      [IDL.Text, ProductId, IDL.Nat, ProductId, IDL.Nat],
      [BuyXGetYRuleId],
      [],
    ),
  'createCategory' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [CategoryId], []),
  'createCoupon' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
        IDL.Nat,
        Timestamp,
        IDL.Nat,
      ],
      [CouponId],
      [],
    ),
  'createFlashDeal' : IDL.Func(
      [ProductId, IDL.Nat, Timestamp, Timestamp],
      [FlashDealId],
      [],
    ),
  'createPriceDropAlert' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Nat],
      [PriceDropAlertId],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CategoryId,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Opt(AgeGatedCategory),
      ],
      [ProductId],
      [],
    ),
  'createRecipe' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(RecipeIngredient),
      ],
      [RecipeId],
      [],
    ),
  'createSeasonalCollection' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Vec(ProductId),
        Timestamp,
        Timestamp,
      ],
      [SeasonalCollectionId],
      [],
    ),
  'createSubscriptionPlan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(SubscriptionItem),
        IDL.Nat,
        SubscriptionFrequency,
      ],
      [SubscriptionPlanId],
      [],
    ),
  'deleteAddress' : IDL.Func([AddressId], [], []),
  'deleteBanner' : IDL.Func([BannerId], [], []),
  'deleteBundle' : IDL.Func([BundleId], [], []),
  'deleteBuyXGetYRule' : IDL.Func([BuyXGetYRuleId], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteCoupon' : IDL.Func([CouponId], [], []),
  'deleteFlashDeal' : IDL.Func([FlashDealId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'deleteRecipe' : IDL.Func([RecipeId], [], []),
  'deleteSeasonalCollection' : IDL.Func([SeasonalCollectionId], [], []),
  'deleteShopLocation' : IDL.Func([ShopLocationId], [], []),
  'deleteSubscriptionPlan' : IDL.Func([SubscriptionPlanId], [], []),
  'generateReferralCode' : IDL.Func([], [IDL.Text], []),
  'generateWishlistShareToken' : IDL.Func([], [IDL.Text], []),
  'getActiveShopLocations' : IDL.Func(
      [],
      [IDL.Vec(ShopLocationPublic)],
      ['query'],
    ),
  'getAdminBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
  'getAdminBuyXGetYRules' : IDL.Func(
      [],
      [IDL.Vec(BuyXGetYRulePublic)],
      ['query'],
    ),
  'getAdminSeasonalCollections' : IDL.Func(
      [],
      [IDL.Vec(SeasonalCollectionPublic)],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllChatThreads' : IDL.Func([], [IDL.Vec(ChatThreadPublic)], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(BannerPublic)], ['query']),
  'getBestSellers' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getBundleById' : IDL.Func([BundleId], [IDL.Opt(BundlePublic)], ['query']),
  'getBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
  'getBuyXGetYRules' : IDL.Func([], [IDL.Vec(BuyXGetYRulePublic)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getChatThread' : IDL.Func([], [IDL.Opt(ChatThreadPublic)], ['query']),
  'getCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getFlashDeals' : IDL.Func([], [IDL.Vec(FlashDealPublic)], ['query']),
  'getInAppNotifications' : IDL.Func(
      [],
      [IDL.Vec(InAppNotificationPublic)],
      ['query'],
    ),
  'getLoyaltyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getLoyaltyHistory' : IDL.Func([], [IDL.Vec(LoyaltyTransaction)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getPriceDropAlerts' : IDL.Func([], [IDL.Vec(PriceDropAlert)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(ProductPublic)], ['query']),
  'getProductReviews' : IDL.Func(
      [ProductId],
      [IDL.Vec(ReviewPublic)],
      ['query'],
    ),
  'getProducts' : IDL.Func(
      [ProductFilters],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'getProductsByIds' : IDL.Func(
      [IDL.Vec(ProductId)],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'getRecipeById' : IDL.Func([RecipeId], [IDL.Opt(RecipePublic)], ['query']),
  'getRecipes' : IDL.Func([], [IDL.Vec(RecipePublic)], ['query']),
  'getReviews' : IDL.Func([IDL.Bool], [IDL.Vec(ReviewPublic)], ['query']),
  'getSeasonalCollections' : IDL.Func(
      [],
      [IDL.Vec(SeasonalCollectionPublic)],
      ['query'],
    ),
  'getSharedWishlist' : IDL.Func([IDL.Text], [IDL.Vec(ProductId)], ['query']),
  'getShopLocations' : IDL.Func([], [IDL.Vec(ShopLocationPublic)], ['query']),
  'getSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlanPublic)],
      ['query'],
    ),
  'getThreadMessages' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserAddresses' : IDL.Func([], [IDL.Vec(SavedAddressPublic)], ['query']),
  'getUserCart' : IDL.Func([], [IDL.Vec(CartItemPublic)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getUserPreferences' : IDL.Func(
      [],
      [IDL.Opt(UserPreferencesPublic)],
      ['query'],
    ),
  'getUserPriceDropAlerts' : IDL.Func([], [IDL.Vec(PriceDropAlert)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserPublic)], []),
  'getUserStockSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(StockSubscription)],
      ['query'],
    ),
  'getUserSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(UserSubscriptionPublic)],
      ['query'],
    ),
  'getUserWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletBonusConfig' : IDL.Func([], [IDL.Nat], ['query']),
  'getWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([InAppNotifId], [], []),
  'placeOrder' : IDL.Func(
      [
        AddressId,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Nat,
      ],
      [PlaceOrderResult],
      [],
    ),
  'rejectReview' : IDL.Func([ReviewId], [], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'resolveThread' : IDL.Func([IDL.Principal], [], []),
  'searchProducts' : IDL.Func(
      [IDL.Text, ProductFilters],
      [IDL.Vec(ProductPublic)],
      ['query'],
    ),
  'sendChatMessage' : IDL.Func([IDL.Text], [ChatMsgId], []),
  'setDefaultAddress' : IDL.Func([AddressId], [], []),
  'setProductFreshness' : IDL.Func(
      [ProductId, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'setSubstituteProduct' : IDL.Func([ProductId, IDL.Opt(IDL.Nat)], [], []),
  'setUserLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'submitReview' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Text, IDL.Text],
      [ReviewId],
      [],
    ),
  'subscribeToPlan' : IDL.Func([SubscriptionPlanId], [UserSubscriptionId], []),
  'subscribeToStockNotification' : IDL.Func([ProductId], [StockSubId], []),
  'topUpWallet' : IDL.Func([IDL.Nat], [], []),
  'triggerStockBackNotifications' : IDL.Func([ProductId], [IDL.Nat], []),
  'unsubscribeFromPlan' : IDL.Func([UserSubscriptionId], [], []),
  'unsubscribeStockNotification' : IDL.Func([ProductId], [], []),
  'updateAddress' : IDL.Func(
      [AddressId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBanner' : IDL.Func(
      [BannerId, ExternalBlob, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateBundle' : IDL.Func(
      [
        BundleId,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Vec(ProductId),
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateBuyXGetYRule' : IDL.Func(
      [
        BuyXGetYRuleId,
        IDL.Text,
        ProductId,
        IDL.Nat,
        ProductId,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateCartQty' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'updateCoupon' : IDL.Func(
      [
        CouponId,
        IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
        IDL.Nat,
        Timestamp,
        IDL.Bool,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateFlashDeal' : IDL.Func(
      [FlashDealId, IDL.Nat, Timestamp, Timestamp, IDL.Bool],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CategoryId,
        ExternalBlob,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Opt(AgeGatedCategory),
      ],
      [],
      [],
    ),
  'updateRecipe' : IDL.Func(
      [
        RecipeId,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(RecipeIngredient),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSeasonalCollection' : IDL.Func(
      [
        SeasonalCollectionId,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Vec(ProductId),
        Timestamp,
        Timestamp,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateShopLocation' : IDL.Func(
      [
        ShopLocationId,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateSubscriptionPlan' : IDL.Func(
      [
        SubscriptionPlanId,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SubscriptionItem),
        IDL.Nat,
        SubscriptionFrequency,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateUserPreferences' : IDL.Func([Language, IDL.Bool], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateWalletBonusConfig' : IDL.Func([IDL.Nat], [], []),
  'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddressId = IDL.Nat;
  const ShopLocationId = IDL.Nat;
  const ProductId = IDL.Nat;
  const ChatMsgId = IDL.Nat;
  const ReviewId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LocationCheckResult = IDL.Variant({
    'noShopLocations' : IDL.Null,
    'withinRadius' : IDL.Record({
      'shopLocationId' : ShopLocationId,
      'distanceKm' : IDL.Float64,
    }),
    'outOfRange' : IDL.Record({ 'nearestDistanceKm' : IDL.Float64 }),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BannerId = IDL.Nat;
  const BundleId = IDL.Nat;
  const BuyXGetYRuleId = IDL.Nat;
  const CategoryId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CouponId = IDL.Nat;
  const FlashDealId = IDL.Nat;
  const PriceDropAlertId = IDL.Nat;
  const AgeGatedCategory = IDL.Variant({
    'Alcohol' : IDL.Null,
    'Tobacco' : IDL.Null,
  });
  const RecipeIngredient = IDL.Record({
    'unit' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Float64,
  });
  const RecipeId = IDL.Nat;
  const SeasonalCollectionId = IDL.Nat;
  const SubscriptionItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const SubscriptionFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const SubscriptionPlanId = IDL.Nat;
  const ShopLocationPublic = IDL.Record({
    'id' : ShopLocationId,
    'lat' : IDL.Float64,
    'long' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'deliveryFeeMultiplier' : IDL.Nat,
    'radiusKm' : IDL.Float64,
  });
  const BundlePublic = IDL.Record({
    'id' : BundleId,
    'imageBlob' : ExternalBlob,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'bundlePrice' : IDL.Nat,
  });
  const BuyXGetYRulePublic = IDL.Record({
    'id' : BuyXGetYRuleId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'getProductId' : ProductId,
    'getQty' : IDL.Nat,
    'buyQty' : IDL.Nat,
    'buyProductId' : ProductId,
  });
  const SeasonalCollectionPublic = IDL.Record({
    'id' : SeasonalCollectionId,
    'imageBlob' : ExternalBlob,
    'endDate' : Timestamp,
    'productIds' : IDL.Vec(ProductId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'startDate' : Timestamp,
  });
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'ordersByDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'lowStockCount' : IDL.Nat,
    'userGrowthByDay' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalUsers' : IDL.Nat,
    'topProducts' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat)),
    'pendingReviews' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalRevenue30Days' : IDL.Nat,
    'activeProducts' : IDL.Nat,
    'totalSavingsDistributed' : IDL.Nat,
  });
  const ChatThreadStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const ChatThreadPublic = IDL.Record({
    'status' : ChatThreadStatus,
    'lastMessageAt' : Timestamp,
    'userId' : UserId,
    'createdAt' : Timestamp,
  });
  const BannerPublic = IDL.Record({
    'id' : BannerId,
    'title' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'displayOrder' : IDL.Nat,
    'link' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
  });
  const ProductPublic = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'imageBlob' : ExternalBlob,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isNewArrival' : IDL.Bool,
    'description' : IDL.Text,
    'ageRestricted' : IDL.Bool,
    'isActive' : IDL.Bool,
    'bestBeforeDate' : IDL.Opt(IDL.Int),
    'isFeatured' : IDL.Bool,
    'rating' : IDL.Nat,
    'bundleId' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
    'reviewCount' : IDL.Nat,
    'isBestSeller' : IDL.Bool,
    'harvestDate' : IDL.Opt(IDL.Int),
    'ageCategory' : IDL.Opt(AgeGatedCategory),
  });
  const CategoryPublic = IDL.Record({
    'id' : CategoryId,
    'displayOrder' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'iconEmoji' : IDL.Text,
  });
  const ChatMessageSender = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : ChatMsgId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'sender' : ChatMessageSender,
  });
  const CouponPublic = IDL.Record({
    'id' : CouponId,
    'discountValue' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
    'usageCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Nat,
    'expirationDate' : Timestamp,
  });
  const FlashDealPublic = IDL.Record({
    'id' : FlashDealId,
    'discountPercent' : IDL.Nat,
    'productId' : ProductId,
    'isActive' : IDL.Bool,
    'endDateTime' : Timestamp,
    'startDateTime' : Timestamp,
  });
  const InAppNotifId = IDL.Nat;
  const InAppNotifType = IDL.Variant({
    'stockBack' : IDL.Null,
    'orderStatus' : IDL.Null,
    'promotion' : IDL.Null,
    'general' : IDL.Null,
    'priceDrop' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const InAppNotificationPublic = IDL.Record({
    'id' : InAppNotifId,
    'title' : IDL.Text,
    'notifType' : InAppNotifType,
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'productId' : IDL.Opt(ProductId),
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(OrderId),
  });
  const LoyaltyTxId = IDL.Nat;
  const LoyaltyReason = IDL.Variant({
    'referral' : IDL.Null,
    'admin' : IDL.Null,
    'purchase' : IDL.Null,
    'redemption' : IDL.Null,
  });
  const LoyaltyTransaction = IDL.Record({
    'id' : LoyaltyTxId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'orderId' : IDL.Opt(OrderId),
    'pointsChange' : IDL.Int,
    'reason' : LoyaltyReason,
  });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'tag' : IDL.Text,
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StatusHistoryEntry = IDL.Record({
    'status' : OrderStatus,
    'timestamp' : Timestamp,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceAtOrder' : IDL.Nat,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'loyaltyPointsRedeemed' : IDL.Nat,
    'total' : IDL.Nat,
    'buyXGetYSavings' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'estimatedDelivery' : IDL.Opt(Timestamp),
    'totalSavings' : IDL.Nat,
    'walletAmountUsed' : IDL.Nat,
    'statusHistory' : IDL.Vec(StatusHistoryEntry),
    'deliverySlot' : IDL.Opt(IDL.Text),
    'couponId' : IDL.Opt(CouponId),
    'items' : IDL.Vec(OrderItem),
    'expressDeliveryFee' : IDL.Nat,
    'isExpressDelivery' : IDL.Bool,
    'subtotal' : IDL.Nat,
  });
  const PriceDropAlert = IDL.Record({
    'id' : PriceDropAlertId,
    'originalPrice' : IDL.Nat,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'alertedUsers' : IDL.Vec(UserId),
    'newPrice' : IDL.Nat,
  });
  const ReviewPublic = IDL.Record({
    'id' : ReviewId,
    'isApproved' : IDL.Bool,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'productId' : ProductId,
    'rating' : IDL.Nat,
    'helpfulCount' : IDL.Nat,
  });
  const ProductFilters = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'minRating' : IDL.Opt(IDL.Nat),
    'onlyActive' : IDL.Bool,
    'maxPrice' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
    'searchQuery' : IDL.Opt(IDL.Text),
  });
  const RecipePublic = IDL.Record({
    'id' : RecipeId,
    'imageBlob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'cookTimeMinutes' : IDL.Nat,
    'isActive' : IDL.Bool,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(RecipeIngredient),
  });
  const SubscriptionPlanPublic = IDL.Record({
    'id' : SubscriptionPlanId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'frequency' : SubscriptionFrequency,
    'items' : IDL.Vec(SubscriptionItem),
    'pricePerCycle' : IDL.Nat,
  });
  const SavedAddressPublic = IDL.Record({
    'id' : AddressId,
    'tag' : IDL.Text,
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'userId' : UserId,
    'state' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const CartItemPublic = IDL.Record({
    'userId' : UserId,
    'productId' : ProductId,
    'addedAt' : Timestamp,
    'substituteProductId' : IDL.Opt(IDL.Nat),
    'quantity' : IDL.Nat,
  });
  const Language = IDL.Variant({
    'EN' : IDL.Null,
    'ES' : IDL.Null,
    'HI' : IDL.Null,
  });
  const UserPreferencesPublic = IDL.Record({
    'userId' : UserId,
    'language' : Language,
    'darkMode' : IDL.Bool,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'userLong' : IDL.Opt(IDL.Float64),
    'referralCode' : IDL.Text,
    'wishlistShareToken' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'userLat' : IDL.Opt(IDL.Float64),
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(UserId),
    'phone' : IDL.Text,
    'loyaltyBalance' : IDL.Nat,
  });
  const StockSubId = IDL.Nat;
  const StockSubscription = IDL.Record({
    'id' : StockSubId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
  });
  const UserSubscriptionId = IDL.Nat;
  const UserSubscriptionPublic = IDL.Record({
    'id' : UserSubscriptionId,
    'planId' : SubscriptionPlanId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'nextDeliveryDate' : Timestamp,
    'isActive' : IDL.Bool,
    'startDate' : Timestamp,
  });
  const WalletTxId = IDL.Nat;
  const WalletTxType = IDL.Variant({
    'topUp' : IDL.Null,
    'adminAdjustment' : IDL.Null,
    'orderDeduction' : IDL.Null,
    'bonus' : IDL.Null,
    'refund' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : WalletTxId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'orderId' : IDL.Opt(OrderId),
    'txType' : WalletTxType,
    'amount' : IDL.Int,
  });
  const PlaceOrderResult = IDL.Variant({ 'ok' : OrderId, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAddress' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AddressId],
        [],
      ),
    'addShopLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
        [ShopLocationId],
        [],
      ),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'adminAdjustWallet' : IDL.Func([IDL.Principal, IDL.Int, IDL.Text], [], []),
    'adminGetAllWallets' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'adminReplyToThread' : IDL.Func([IDL.Principal, IDL.Text], [ChatMsgId], []),
    'approveReview' : IDL.Func([ReviewId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkDeliveryRadius' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [LocationCheckResult],
        ['query'],
      ),
    'clearCart' : IDL.Func([], [], []),
    'createBanner' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Text, IDL.Nat],
        [BannerId],
        [],
      ),
    'createBundle' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Vec(ProductId), IDL.Nat],
        [BundleId],
        [],
      ),
    'createBuyXGetYRule' : IDL.Func(
        [IDL.Text, ProductId, IDL.Nat, ProductId, IDL.Nat],
        [BuyXGetYRuleId],
        [],
      ),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [CategoryId],
        [],
      ),
    'createCoupon' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
          IDL.Nat,
          Timestamp,
          IDL.Nat,
        ],
        [CouponId],
        [],
      ),
    'createFlashDeal' : IDL.Func(
        [ProductId, IDL.Nat, Timestamp, Timestamp],
        [FlashDealId],
        [],
      ),
    'createPriceDropAlert' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Nat],
        [PriceDropAlertId],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CategoryId,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Opt(AgeGatedCategory),
        ],
        [ProductId],
        [],
      ),
    'createRecipe' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(RecipeIngredient),
        ],
        [RecipeId],
        [],
      ),
    'createSeasonalCollection' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Vec(ProductId),
          Timestamp,
          Timestamp,
        ],
        [SeasonalCollectionId],
        [],
      ),
    'createSubscriptionPlan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(SubscriptionItem),
          IDL.Nat,
          SubscriptionFrequency,
        ],
        [SubscriptionPlanId],
        [],
      ),
    'deleteAddress' : IDL.Func([AddressId], [], []),
    'deleteBanner' : IDL.Func([BannerId], [], []),
    'deleteBundle' : IDL.Func([BundleId], [], []),
    'deleteBuyXGetYRule' : IDL.Func([BuyXGetYRuleId], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteCoupon' : IDL.Func([CouponId], [], []),
    'deleteFlashDeal' : IDL.Func([FlashDealId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'deleteRecipe' : IDL.Func([RecipeId], [], []),
    'deleteSeasonalCollection' : IDL.Func([SeasonalCollectionId], [], []),
    'deleteShopLocation' : IDL.Func([ShopLocationId], [], []),
    'deleteSubscriptionPlan' : IDL.Func([SubscriptionPlanId], [], []),
    'generateReferralCode' : IDL.Func([], [IDL.Text], []),
    'generateWishlistShareToken' : IDL.Func([], [IDL.Text], []),
    'getActiveShopLocations' : IDL.Func(
        [],
        [IDL.Vec(ShopLocationPublic)],
        ['query'],
      ),
    'getAdminBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
    'getAdminBuyXGetYRules' : IDL.Func(
        [],
        [IDL.Vec(BuyXGetYRulePublic)],
        ['query'],
      ),
    'getAdminSeasonalCollections' : IDL.Func(
        [],
        [IDL.Vec(SeasonalCollectionPublic)],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllChatThreads' : IDL.Func([], [IDL.Vec(ChatThreadPublic)], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(BannerPublic)], ['query']),
    'getBestSellers' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getBundleById' : IDL.Func([BundleId], [IDL.Opt(BundlePublic)], ['query']),
    'getBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
    'getBuyXGetYRules' : IDL.Func([], [IDL.Vec(BuyXGetYRulePublic)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getChatThread' : IDL.Func([], [IDL.Opt(ChatThreadPublic)], ['query']),
    'getCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getFlashDeals' : IDL.Func([], [IDL.Vec(FlashDealPublic)], ['query']),
    'getInAppNotifications' : IDL.Func(
        [],
        [IDL.Vec(InAppNotificationPublic)],
        ['query'],
      ),
    'getLoyaltyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getLoyaltyHistory' : IDL.Func(
        [],
        [IDL.Vec(LoyaltyTransaction)],
        ['query'],
      ),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getPriceDropAlerts' : IDL.Func([], [IDL.Vec(PriceDropAlert)], ['query']),
    'getProductById' : IDL.Func(
        [ProductId],
        [IDL.Opt(ProductPublic)],
        ['query'],
      ),
    'getProductReviews' : IDL.Func(
        [ProductId],
        [IDL.Vec(ReviewPublic)],
        ['query'],
      ),
    'getProducts' : IDL.Func(
        [ProductFilters],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'getProductsByIds' : IDL.Func(
        [IDL.Vec(ProductId)],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'getRecipeById' : IDL.Func([RecipeId], [IDL.Opt(RecipePublic)], ['query']),
    'getRecipes' : IDL.Func([], [IDL.Vec(RecipePublic)], ['query']),
    'getReviews' : IDL.Func([IDL.Bool], [IDL.Vec(ReviewPublic)], ['query']),
    'getSeasonalCollections' : IDL.Func(
        [],
        [IDL.Vec(SeasonalCollectionPublic)],
        ['query'],
      ),
    'getSharedWishlist' : IDL.Func([IDL.Text], [IDL.Vec(ProductId)], ['query']),
    'getShopLocations' : IDL.Func([], [IDL.Vec(ShopLocationPublic)], ['query']),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlanPublic)],
        ['query'],
      ),
    'getThreadMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserAddresses' : IDL.Func([], [IDL.Vec(SavedAddressPublic)], ['query']),
    'getUserCart' : IDL.Func([], [IDL.Vec(CartItemPublic)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getUserPreferences' : IDL.Func(
        [],
        [IDL.Opt(UserPreferencesPublic)],
        ['query'],
      ),
    'getUserPriceDropAlerts' : IDL.Func(
        [],
        [IDL.Vec(PriceDropAlert)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserPublic)], []),
    'getUserStockSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(StockSubscription)],
        ['query'],
      ),
    'getUserSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(UserSubscriptionPublic)],
        ['query'],
      ),
    'getUserWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletBonusConfig' : IDL.Func([], [IDL.Nat], ['query']),
    'getWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([InAppNotifId], [], []),
    'placeOrder' : IDL.Func(
        [
          AddressId,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Nat,
        ],
        [PlaceOrderResult],
        [],
      ),
    'rejectReview' : IDL.Func([ReviewId], [], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'resolveThread' : IDL.Func([IDL.Principal], [], []),
    'searchProducts' : IDL.Func(
        [IDL.Text, ProductFilters],
        [IDL.Vec(ProductPublic)],
        ['query'],
      ),
    'sendChatMessage' : IDL.Func([IDL.Text], [ChatMsgId], []),
    'setDefaultAddress' : IDL.Func([AddressId], [], []),
    'setProductFreshness' : IDL.Func(
        [ProductId, IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'setSubstituteProduct' : IDL.Func([ProductId, IDL.Opt(IDL.Nat)], [], []),
    'setUserLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'submitReview' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Text, IDL.Text],
        [ReviewId],
        [],
      ),
    'subscribeToPlan' : IDL.Func(
        [SubscriptionPlanId],
        [UserSubscriptionId],
        [],
      ),
    'subscribeToStockNotification' : IDL.Func([ProductId], [StockSubId], []),
    'topUpWallet' : IDL.Func([IDL.Nat], [], []),
    'triggerStockBackNotifications' : IDL.Func([ProductId], [IDL.Nat], []),
    'unsubscribeFromPlan' : IDL.Func([UserSubscriptionId], [], []),
    'unsubscribeStockNotification' : IDL.Func([ProductId], [], []),
    'updateAddress' : IDL.Func(
        [AddressId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBanner' : IDL.Func(
        [BannerId, ExternalBlob, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateBundle' : IDL.Func(
        [
          BundleId,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Vec(ProductId),
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateBuyXGetYRule' : IDL.Func(
        [
          BuyXGetYRuleId,
          IDL.Text,
          ProductId,
          IDL.Nat,
          ProductId,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateCartQty' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'updateCoupon' : IDL.Func(
        [
          CouponId,
          IDL.Variant({ 'fixed' : IDL.Null, 'percent' : IDL.Null }),
          IDL.Nat,
          Timestamp,
          IDL.Bool,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateFlashDeal' : IDL.Func(
        [FlashDealId, IDL.Nat, Timestamp, Timestamp, IDL.Bool],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CategoryId,
          ExternalBlob,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Opt(AgeGatedCategory),
        ],
        [],
        [],
      ),
    'updateRecipe' : IDL.Func(
        [
          RecipeId,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(RecipeIngredient),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSeasonalCollection' : IDL.Func(
        [
          SeasonalCollectionId,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Vec(ProductId),
          Timestamp,
          Timestamp,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateShopLocation' : IDL.Func(
        [
          ShopLocationId,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateSubscriptionPlan' : IDL.Func(
        [
          SubscriptionPlanId,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SubscriptionItem),
          IDL.Nat,
          SubscriptionFrequency,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateUserPreferences' : IDL.Func([Language, IDL.Bool], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateWalletBonusConfig' : IDL.Func([IDL.Nat], [], []),
    'validateInviteCode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };